export const firstAidGuides = {
  cardiac: {
    title: 'Cardiac Emergency',
    color: '#ff2233',
    steps: [
      { icon: '📞', text: 'Call SOS immediately — every minute counts in cardiac arrest' },
      { icon: '🛋️', text: 'Help patient sit or lie flat in a comfortable position' },
      { icon: '👔', text: 'Loosen tight clothing around the chest, neck, and waist' },
      { icon: '🫀', text: 'If unresponsive + no breathing: begin CPR — 30 hard chest compressions, 2 rescue breaths' },
      { icon: '💊', text: 'If patient is conscious and not allergic, give one aspirin (325mg) to chew' },
      { icon: '🚫', text: 'Do NOT give food, water, or allow patient to walk' },
      { icon: '👁️', text: 'Monitor breathing every 2 minutes until ambulance arrives' },
    ],
  },
  neurological: {
    title: 'Neurological Emergency',
    color: '#00d4ff',
    steps: [
      { icon: '⚡', text: 'Use FAST test: Face drooping, Arm weak, Speech slurred → Time to call SOS' },
      { icon: '🛑', text: 'Do NOT move the patient\'s head or neck in case of spinal injury' },
      { icon: '↩️', text: 'If unconscious but breathing: place in recovery position (on their side)' },
      { icon: '⏱️', text: 'Note exact time symptoms began — critical for stroke treatment window' },
      { icon: '🚫', text: 'Do not give anything by mouth — risk of choking' },
      { icon: '🌡️', text: 'Keep patient calm and at normal temperature — no cold water' },
      { icon: '💬', text: 'Talk calmly to the patient even if they appear unconscious' },
    ],
  },
  trauma: {
    title: 'Trauma / Accident',
    color: '#ffb000',
    steps: [
      { icon: '🩹', text: 'Apply firm pressure to bleeding wounds using clean cloth — maintain continuously' },
      { icon: '🔩', text: 'Do NOT remove embedded objects — they may be controlling bleeding' },
      { icon: '🦺', text: 'If neck or spine injury suspected: keep head still using both hands' },
      { icon: '⬆️', text: 'Elevate injured limb above heart level if no fracture suspected' },
      { icon: '🧣', text: 'Keep patient warm — shock causes rapid heat loss' },
      { icon: '😮‍💨', text: 'Watch for shock: pale skin, rapid weak pulse, confusion, fainting' },
      { icon: '🚫', text: 'Do not move patient unless in immediate danger (fire, traffic)' },
    ],
  },
  toxicological: {
    title: 'Toxicological Emergency',
    color: '#00ff88',
    steps: [
      { icon: '🐍', text: 'Snake bite: immobilize bitten limb, keep below heart level, remove watches/rings' },
      { icon: '🚫', text: 'Do NOT cut, suck, or apply tourniquet to snake bite — these cause more harm' },
      { icon: '💊', text: 'Poisoning: do NOT induce vomiting unless specifically instructed by medical staff' },
      { icon: '📝', text: 'Note: time of exposure, substance name, and amount — tell paramedics' },
      { icon: '💧', text: 'Chemical on skin: remove contaminated clothing, rinse skin with water 15–20 min' },
      { icon: '👁️', text: 'Chemical in eyes: rinse with clean water for 15 minutes continuously' },
      { icon: '🧘', text: 'Keep patient still and calm — movement speeds toxin absorption' },
    ],
  },
  respiratory: {
    title: 'Respiratory Emergency',
    color: '#00d4ff',
    steps: [
      { icon: '🪑', text: 'Sit patient upright, leaning slightly forward — never lay flat' },
      { icon: '💨', text: 'If patient has an inhaler: assist them in using it immediately' },
      { icon: '👔', text: 'Loosen all tight clothing around neck, chest, and waist' },
      { icon: '🌬️', text: 'Provide fresh air — open windows, move away from smoke/fumes' },
      { icon: '🧘', text: 'Coach slow breathing: inhale 4 sec, hold 1 sec, exhale 6 sec' },
      { icon: '🔵', text: 'If lips or fingernails turn blue: begin rescue breathing immediately' },
      { icon: '😌', text: 'Keep patient calm — panic worsens breathing difficulty significantly' },
    ],
  },
  general: {
    title: 'General Emergency',
    color: '#c8dff0',
    steps: [
      { icon: '🤚', text: 'Assess responsiveness: call their name, gently tap shoulders' },
      { icon: '😮‍💨', text: 'Check breathing: look for chest rise, listen, feel for breath on cheek' },
      { icon: '↩️', text: 'If unconscious and breathing: recovery position on their side' },
      { icon: '🫀', text: 'If not breathing: start CPR — 30 compressions + 2 breaths, repeat' },
      { icon: '🌡️', text: 'Keep patient warm and comfortable — use blanket if available' },
      { icon: '📋', text: 'Monitor vital signs every 2 minutes and report changes to dispatcher' },
      { icon: '🗣️', text: 'Reassure the patient: "Help is on the way, I\'m here with you"' },
    ],
  },
}
